FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ \
     && pip config set global.trusted-host mirrors.aliyun.com \
     && python -m pip install --no-cache-dir --default-timeout=120 -r /app/requirements.txt

COPY . /app

CMD ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]